const apiConfig = {
  uuidKey: '123456',
  obBaseUrl: 'https://sdk-mokserver.onrender.com/sdk/',
  ibanBaseUrl: 'https://sdk-mokserver.onrender.com/sdk/',

  obApiKey:
    'eyJ4NXQiOiJPREUzWTJaaE1UQmpNRE00WlRCbU1qQXlZemxpWVRJMllqUmhZVFpsT0dJeVptVXhOV0UzWVE9PSIsImtpZCI6ImdhdGV3YXlfY2VydGlmaWNhdGVfYWxpYXMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJhcHBsaWNhdGlvbiI6eyJvd25lciI6ImFkbWluIiwidGllclF1b3RhVHlwZSI6bnVsbCwidGllciI6IjIwUGVyTWluIiwibmFtZSI6IlNESyIsImlkIjoxMTUsInV1aWQiOiJlNjgxYzZjNS1kNjBiLTRiMGItYWY2MC1jMDY2YzQwYjRhYzgifSwiaXNzIjoiaHR0cHM6XC9cL2FtLXdzbzItbm9ucHJvZC5hcHBzLm50LW5vbi1vY3AubmVvdGVrLnNhOjQ0M1wvb2F1dGgyXC90b2tlbiIsInRpZXJJbmZvIjp7IlVubGltaXRlZCI6eyJ0aWVyUXVvdGFUeXBlIjoicmVxdWVzdENvdW50IiwiZ3JhcGhRTE1heENvbXBsZXhpdHkiOjAsImdyYXBoUUxNYXhEZXB0aCI6MCwic3RvcE9uUXVvdGFSZWFjaCI6dHJ1ZSwic3Bpa2VBcnJlc3RMaW1pdCI6MCwic3Bpa2VBcnJlc3RVbml0IjpudWxsfX0sImtleXR5cGUiOiJQUk9EVUNUSU9OIiwicGVybWl0dGVkUmVmZXJlciI6IiIsInN1YnNjcmliZWRBUElzIjpbeyJzdWJzY3JpYmVyVGVuYW50RG9tYWluIjoiY2FyYm9uLnN1cGVyIiwibmFtZSI6InFhZW1hLW9wZW4tYmFua2luZyIsImNvbnRleHQiOiJcL3FhZW1hXC9vYlwvdjEiLCJwdWJsaXNoZXIiOiJhZG1pbiIsInZlcnNpb24iOiJ2MSIsInN1YnNjcmlwdGlvblRpZXIiOiJVbmxpbWl0ZWQifSx7InN1YnNjcmliZXJUZW5hbnREb21haW4iOiJjYXJib24uc3VwZXIiLCJuYW1lIjoiU0RLcyIsImNvbnRleHQiOiJcL3Nka1wvMS4wIiwicHVibGlzaGVyIjoiYWRtaW4iLCJ2ZXJzaW9uIjoiMS4wIiwic3Vic2NyaXB0aW9uVGllciI6IlVubGltaXRlZCJ9XSwidG9rZW5fdHlwZSI6ImFwaUtleSIsInBlcm1pdHRlZElQIjoiIiwiaWF0IjoxNzI0NzkzODc1LCJqdGkiOiI3MGVkZDIxYy01Yjc4LTQ1YjgtYjkyMC0xNDRmZTQ3MTllZmMifQ==.ZXOFArTNfkeVa9Nh-SCU04RtAmEUYWcDKlpJXpEsM1KRl_2On86rtwkjKiL6UhRcc6lZGk8L9BdcXJToJTx-mXnUdlqWJzEuWUz8k0xnknQCq72BWZhfhMhHf43SFnGNIUbi8JIAYNcUMHOQY8lNbYqcefjfphJ_IlfbRAqjzUTE4JcIXYZjZXLSale9AOHhG0oOCb_TcB1600xm_UGDcvOPurrTrNtC9wuB3oT-wYfZyECywE0szKPvfB0VJYqb4laamestTLM73AC73Sxuy-ZqWIU21FjWEEq0YsEM3SgPepbgfg3xC9fql79UwEqaPoiWR_3wf8NjJWsBACjjxw==',
  ibanApiKey:
    'AAIgZDkwNWI1OTEyY2RjNmMwNjZiNjY3MmViOTQ2ZjE4Zjar7pqq6kCKhv53PWDuVfKhhX4TgNWrCXzUCnaOldtfHoW4mplutNWVewomH66etFinWYZy7vo9Whx1RiZ_XhToLXzCDlk5KEYtOlRrgL-8HtY8Ww9evsmThyLYWKnr3mQCyBIF19IWx9yUL6lQqBg0L7Rd5DT_tmp7bzimb3pNXe0gpkQihH4nYoEcZYvSUTA',

  psuId: '',
  clientId: '',
  clientSecret: '',
};

// Function to set dynamic values from the consumer app
export const setApiConfig = (config: {
  psuId: string;
  clientId: string;
  clientSecret: string;
}) => {
  apiConfig.psuId = config.psuId;
  apiConfig.clientId = config.clientId;
  apiConfig.clientSecret = config.clientSecret;
};

export default apiConfig;
