// export const OB_REST_ENDPOINTS = {
//   OBAUTH: 'oauth2security/oauth2/token',
//   OBPSUSERS: 'client-managed-profiles/v1/psusers/',
//   FINANCIAL_INSTITUTION:
//     'financial-institutions-information/v1/financial-institutions',
//   FINANCIAL_INSTITUTION_DATA_GROUPS: '/data-groups',
//   BANKS: 'banks',
//   PSU_USERS: 'psusers/',
//   ACCOUNTS: 'accounts',
//   PROFILE_ACCOUNTS_INFO: 'profile-accounts-information/v1/',
//   GET_LINK: 'get/accountLink',
//   CREATE_LINK: 'create/accountLink',
//   UPDATE_LINK: 'update/accountLink',
//   DELETE_LINK: 'delete/accountLink',
//   ACCOUNT: 'account/getAccounts',
//   TRANSACTIONS: 'transactions',
//   AGGREGATED_BALANCES: 'AggregatedBalances',
//   BALANCES: 'balances',
//   ACTIVATE: 'activate',
//   ACCOUNTS_LINKS: 'accounts-links',
//   PROFILES: 'profiles/',
//   SELF_MANAGED_PROFILES: 'self-managed-profiles/v1/',
//   NICKNAME: '/financial-institution-nickname',
// };
